version: '3'

services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:8080"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypass

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
